name: Build Console Sample

on:
  workflow_dispatch:

jobs:
  linux-build:
    name: 'Linux'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      
      - name: 1. Setup Python
        id: setup_python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: 2. Generate Python venv cache
        id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-2-3.8

      - name: 3. Install Python dependencies unless cached
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          # Check if venv exists (restored from secondary keys if any, and delete)
          if [ -d "venv" ]; then rm -rf venv; fi
          # Re-create the venv
          python3 -m venv venv
          # Upgrade pip
          venv/bin/python3 -m pip install --upgrade pip
          # Install dependencies
          venv/bin/python3 -m pip install pyinstaller setuptools
          venv/bin/python3 -m pip install patchelf-wrapper staticx
          
      - name: 4. Run PyInstaller
        run: |
          venv/bin/pyinstaller --path="$(pwd)" --onefile --clean --name="sample" ./sample-python-console-app.py
        
      - name: 5. Run StaticX
        run: venv/bin/staticx --loglevel DEBUG ./dist/sample ./dist/sample-static
        
      - name: 6. Upload the build artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: staticx-linux-console-sample
          path: ./dist/
          if-no-files-found: error
          retention-days: 1
